###GET de todos los articulos. Se debe de pasar por query params:
#order_column: La columna por la que se ordenara.
#asc: "ASC" si la query es rellenada, "DESC" si esta  vacia
#limit.
#offset.

GET http://localhost:3000/api/articulos?order_column=id_area&&direction=DESC&&limit=10&&offset=0


###GET de articulos, agregando filtros extra (id_area, id_categoria, descripcion)
###por area:

GET http://localhost:3000/api/articulos?order_column=id_area&&direction=desc&&limit=10&&offset=0&&id_area=2

###Por categoria:

GET http://localhost:3000/api/articulos?order_column=id_area&&direction=asc&&limit=10&&offset=0&&id_categoria=1

###Por descripcion:

GET http://localhost:3000/api/articulos?order_column=id_area&&direction=desc&&limit=10&&offset=0&&descripcion=not

###Por todo a la vez:

GET http://localhost:3000/api/articulos?order_column=id_area&&direction=ASC&&limit=10&&offset=0&&id_area=1&&id_categoria=1&&descripcion=not




###GET de articulos por id
#Se pasa por route params el id

GET http://localhost:3000/api/articulos/2


###Actualizar articulo por id
#Se pasan por body los campos a cambiar
#Por ahora da error enviar el body vacio...
PATCH http://localhost:3000/api/articulos/1
Content-Type: application/json

{
    "id_area": 2
}


###POST
#Se pasan por body todos los valores (id_area, id_categoria, descripcion y activo)
POST http://localhost:3000/api/articulos
Content-Type: application/json

{
    "id_area": 3,
    "id_categoria": 5,
    "descripcion": "noc2",
    "activo": 0
}

####DELETE
#Se borra logicamente el articulo segun el id
DELETE http://localhost:3000/api/articulos/8
